import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navigation/navbar";
import Footer from "@/components/navigation/footer";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100","200", "300", "400", "500", "600", "800", "900"],
  variable: "--font-poppins"
})

export const metadata = {
  title: "Job Hunt Helper",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable}  antialiased`}
      >
         <Navbar />
        {children}
         <Footer />
      </body>
    </html>
  );
}
